language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - php -d memory_limit=-1 composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
