language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

#before_install: echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini


install:
    #- php -d memory_limit=-1 /usr/local/bin/composer update --verbose --profile
    - composer install --prefer-source --no-interaction --dev --profile
    #- composer install --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
